about:
  type: book
  title: Free Culture
  author: Lawrence Lessig
  year: 2004
  keywords:
    - culture
    - free culture
    - copyright law
    - intellectual property
    - public domain
    - web
    - internet
    - mp3
    - Napster
dirs:
  text: text
  bibliography: bib
  dictionary: dictionary
  templates: templates
  assets: assets
  style: style
  scripts: scripts
